"""Pure domain types: enums, error hierarchy, and DTOs.

Re-exported here so callers can write
`from opstools.inventory_forecast.domain import SourceKind` without reaching
into submodules. This layer imports nothing else of ours (ARCHITECTURE.md
§4.1): `domain` is the foundation everything else depends on.
"""

from opstools.inventory_forecast.domain.contracts import (
    CLOSING_STOCK_NON_NULL_COLUMNS,
    CLOSING_STOCK_REQUIRED_COLUMNS,
    ERP_TRANSACTION_COLUMNS,
    GRN_REQUIRED_COLUMNS,
    POV_REQUIRED_COLUMNS,
    PV_REQUIRED_COLUMNS,
    TRANSACTION_NON_NULL_COLUMNS,
    TRANSACTION_REQUIRED_COLUMNS,
)
from opstools.inventory_forecast.domain.enums import (
    AbcClass,
    ForecastGranularity,
    ForecastModel,
    ForecastStatus,
    FulfillmentStatus,
    InventoryStatus,
    RiskLevel,
    SbcClass,
    SourceKind,
    SupplierDependencyLevel,
    TrendDirection,
)
from opstools.inventory_forecast.domain.errors import (
    BacktestingError,
    ClassificationError,
    DashboardGenerationError,
    DataValidationError,
    DuplicateRecordError,
    FillRateError,
    ForecastingError,
    InsufficientHistoryError,
    InvalidSchemaError,
    InventoryAnalyticsError,
    InventoryForecastError,
    InventoryHealthError,
    LeadTimeError,
    MissingColumnError,
    ModelSelectionError,
    ReorderCalculationError,
    SecurityError,
    SourcingRiskError,
    SupplierAnalyticsError,
    WorkbookError,
    WorksheetGenerationError,
    WorksheetMetaDataError,
)
from opstools.inventory_forecast.domain.models import (
    AnalyticsSummary,
    DemandCharacteristics,
    DemandObservation,
    ForecastMetrics,
    ForecastRequest,
    ForecastResult,
    InventoryHealthReport,
    ReplenishmentRecommendation,
    SourceSet,
    SupplierPerformance,
    SupplierRisk,
    WorkbookMeta,
)
from opstools.inventory_forecast.domain.validation import (
    validate_closing_stock,
    validate_transaction_dataset,
)

__all__ = (
    "CLOSING_STOCK_NON_NULL_COLUMNS",
    "CLOSING_STOCK_REQUIRED_COLUMNS",
    "ERP_TRANSACTION_COLUMNS",
    "GRN_REQUIRED_COLUMNS",
    "POV_REQUIRED_COLUMNS",
    "PV_REQUIRED_COLUMNS",
    "TRANSACTION_NON_NULL_COLUMNS",
    "TRANSACTION_REQUIRED_COLUMNS",
    "AbcClass",
    "AnalyticsSummary",
    "BacktestingError",
    "ClassificationError",
    "DashboardGenerationError",
    "DataValidationError",
    "DemandCharacteristics",
    "DemandObservation",
    "DuplicateRecordError",
    "FillRateError",
    "ForecastGranularity",
    "ForecastMetrics",
    "ForecastModel",
    "ForecastRequest",
    "ForecastResult",
    "ForecastStatus",
    "ForecastingError",
    "FulfillmentStatus",
    "InsufficientHistoryError",
    "InvalidSchemaError",
    "InventoryAnalyticsError",
    "InventoryForecastError",
    "InventoryHealthError",
    "InventoryHealthReport",
    "InventoryStatus",
    "LeadTimeError",
    "MissingColumnError",
    "ModelSelectionError",
    "ReorderCalculationError",
    "ReplenishmentRecommendation",
    "RiskLevel",
    "SbcClass",
    "SecurityError",
    "SourceKind",
    "SourceSet",
    "SourcingRiskError",
    "SupplierAnalyticsError",
    "SupplierDependencyLevel",
    "SupplierPerformance",
    "SupplierRisk",
    "TrendDirection",
    "WorkbookError",
    "WorkbookMeta",
    "WorksheetGenerationError",
    "WorksheetMetaDataError",
    "validate_closing_stock",
    "validate_transaction_dataset",
)
