"""Canonical domain models for the inventory forecasting system.

These models define the business contracts exchanged between
application layers. They are intentionally independent of
Polars, StatsForecast, Excel workbooks, dashboards, and
external infrastructure.

Engine modules perform calculations.

Domain models describe business reality.
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from .enums import (
    ForecastModel,
    ForecastStatus,
    InventoryStatus,
    RiskLevel,
    SbcClass,
    SourceKind,
    SupplierDependencyLevel,
)


class SourceSet(BaseModel):
    """The grouped input files for a single pipeline run.

    Each ERP report type may arrive as several files (e.g. one per year —
    INPUT_SCHEMA.md "Multiple yearly input files"), so each field is a tuple of
    paths. Tuples (not lists) keep the model genuinely immutable and hashable,
    supporting reproducibility (Constitution Rule 9). File existence/validity is
    checked later at the ingestion boundary, not here.
    """

    model_config = ConfigDict(frozen=True)

    pov: tuple[Path, ...] = ()
    grn: tuple[Path, ...] = ()
    pv: tuple[Path, ...] = ()
    closing_stock: tuple[Path, ...] = ()

    def iter_with_kind(self) -> Iterator[tuple[Path, SourceKind]]:
        """Yield every (path, kind) pair across all four report groups.

        Ingestion will loop over this to dispatch each file to the right
        reader, so the (path, kind) pairing lives with the data, not in caller
        code.
        """
        for path in self.pov:
            yield path, SourceKind.POV
        for path in self.grn:
            yield path, SourceKind.GRN
        for path in self.pv:
            yield path, SourceKind.PV
        for path in self.closing_stock:
            yield path, SourceKind.CLOSING_STOCK

    @property
    def all_paths(self) -> tuple[Path, ...]:
        """All input paths across the four groups, in canonical order."""
        return self.pov + self.grn + self.pv + self.closing_stock


class WorkbookMeta(BaseModel):
    """Provenance and run statistics written to the Metadata sheet.

    Mirrors the Metadata sheet columns in WORKBOOK_SCHEMA.md and the authenticity
    controls in THREAT_MODEL.md. `generated_at` is the only sanctioned place for
    wall-clock time (Constitution Rule 9): it lives in metadata, never in
    business logic.
    """

    model_config = ConfigDict(frozen=True)

    schema_version: str
    application_version: str
    generated_at: datetime
    source_hash: str
    output_hash: str
    forecast_horizon: int = Field(gt=0)
    total_suppliers: int = Field(ge=0)
    total_items: int = Field(ge=0)
    total_records: int = Field(ge=0)
    processing_time_seconds: float = Field(ge=0.0)


@dataclass(frozen=True, slots=True)
class DemandCharacteristics:
    """Statistical profile of an item's historical demand.

    Generated by the demand-classification subsystem and used
    to determine the most appropriate forecasting strategy.

    Attributes:
        item_id:
            Unique inventory item identifier.

        history_length:
            Number of historical observations available.

        mean_demand:
            Average demand across the historical period.

        std_demand:
            Standard deviation of historical demand.

        adi:
            Average Demand Interval (ADI), representing the
            average number of periods between non-zero demand.

        cv2:
            Squared Coefficient of Variation (CV^2), used in
            Syntetos-Boylan demand classification.

        zero_demand_ratio:
            Fraction of periods with zero demand.

        demand_class:
            SBC demand classification assigned to the item.
    """

    item_id: str

    history_length: int

    mean_demand: float
    std_demand: float

    adi: float
    cv2: float

    zero_demand_ratio: float

    demand_class: SbcClass

    def __post_init__(self) -> None:
        """Validate demand characteristics."""
        if self.history_length <= 0:
            raise ValueError("history_length must be positive.")

        if self.adi < 0:
            raise ValueError("adi must be positive.")

        if self.cv2 < 0:
            raise ValueError("cv2 must be positive.")

        if not 0.0 <= self.zero_demand_ratio <= 1.0:
            raise ValueError("zero_demand_ratio must be between 0 and 1.0.")


@dataclass(frozen=True, slots=True)
class DemandObservation:
    """Reconstructed demand event derived from inventory replenishment behaviour.

    Attributes:
        item_id:
            Inventory item identifier.

        observation_date:
            Date associated with the inferred demand event.

        quantity:
            Reconstructed demand quantity.
    """

    item_id: str

    observation_date: date

    quantity: float

    def __post_init__(self) -> None:
        """Validate demand observation result."""
        if self.quantity < 0:
            raise ValueError("quantity cannot be negative.")


@dataclass(frozen=True, slots=True)
class ForecastRequest:
    """Input contract for forecast generation.

    Encapsulates all configuration required to produce a
    demand forecast for a single inventory item.

    This model serves as the public entry point into the
    forecasting subsystem.

    Attributes:
        item_id:
            Unique inventory item identifier.

        horizon:
            Number of future periods to forecast.

        seasonality:
            Seasonal cycle length used by seasonal models.

        service_level:
            Target service level expressed as a decimal
            probability between 0 and 1.
    """

    item_id: str

    horizon: int

    seasonality: int

    service_level: float

    def __post_init__(self) -> None:
        """Validate forecast request."""
        if self.horizon <= 0:
            raise ValueError("horizon must be positive.")

        if self.seasonality <= 0:
            raise ValueError("seasonality must be positive.")

        if not 0.0 <= self.service_level <= 1.0:
            raise ValueError("service_level must be between 0 and 1.0.")


@dataclass(frozen=True, slots=True)
class ForecastMetrics:
    """Forecast performance metrics produced during model evaluation and backtesting.

    These metrics are used to compare competing forecast
    models and select the best-performing model for a
    specific inventory item.

    Attributes:
        mase:
            Mean Absolute Scaled Error.

        rmsse:
            Root Mean Squared Scaled Error.

        bias:
            Average forecast bias. Positive values indicate
            overforecasting while negative values indicate
            underforecasting.

        mae:
            Mean Absolute Error.

        rmse:
            Root Mean Squared Error.

        observation_count:
            Number of observations used during evaluation.
    """

    mase: float

    rmsse: float

    bias: float

    mae: float

    rmse: float

    observation_count: int

    def __post_init__(self) -> None:
        """Validate metric values."""
        if self.mase < 0:
            raise ValueError("MASE cannot be negative.")

        if self.rmsse < 0:
            raise ValueError("RMSSE cannot be negative.")

        if self.mae < 0:
            raise ValueError("MAE cannot be negative.")

        if self.rmse < 0:
            raise ValueError("RMSE cannot be negative.")

        if self.observation_count <= 0:
            raise ValueError("Observation count must be positive.")


@dataclass(frozen=True, slots=True)
class ForecastResult:
    """Final demand forecast produced for an inventory item.

    Represents the selected forecasting model, forecasted
    demand values, prediction intervals, and model
    evaluation metrics.

    This is the primary output of the forecasting subsystem
    and serves as an input to replenishment planning and
    inventory analytics.

    Attributes:
        item_id:
            Unique inventory item identifier.

        demand_class:
            SBC demand classification assigned during
            demand analysis.

        selected_model:
            Forecasting model selected after evaluation.

        forecast_values:
            Forecasted demand quantities for future periods.

        lower_bound:
            Lower prediction interval values corresponding
            to each forecast period.

        upper_bound:
            Upper prediction interval values corresponding
            to each forecast period.

        metrics:
            Forecast evaluation metrics generated during
            backtesting.

        status:
            Forecast status after evaluation.

        generated_at:
            UTC timestamp indicating when the forecast
            was produced.
    """

    item_id: str

    demand_class: SbcClass

    selected_model: ForecastModel

    forecast_values: tuple[float, ...]

    lower_bound: tuple[float, ...]

    upper_bound: tuple[float, ...]

    metrics: ForecastMetrics

    status: ForecastStatus

    generated_at: datetime

    def __post_init__(self) -> None:
        """Validate forecast result."""
        expected = len(self.forecast_values)

        if expected == 0:
            raise ValueError("forecast_values cannot be empty.")

        if len(self.lower_bound) != expected:
            raise ValueError("lower_bound length must match forecast_values length.")

        if len(self.upper_bound) != expected:
            raise ValueError("upper_bound length must match forecast_values length.")


@dataclass(frozen=True, slots=True)
class SupplierPerformance:
    """Historical supplier performance metrics for an item.

    Produced from purchase-order and goods-receipt analysis
    to evaluate supplier reliability and delivery behaviour.

    Attributes:
        supplier_id:
            Supplier identifier.

        item_id:
            Unique inventory item identifier.

        avg_lead_time_days:
            Average supplier lead time in days.

        lead_time_std_dev:
            Standard deviation of supplier lead times.

        avg_fill_rate:
            Average proportion of ordered quantity successfully delivered.
    """

    supplier_id: str
    item_id: str

    avg_lead_time_days: float
    lead_time_std_dev: float
    avg_fill_rate: float


@dataclass(frozen=True, slots=True)
class SupplierRisk:
    """Supplier concentration and dependency risk assessment.

    Quantifies the operational risk associated with supplier
    concentration for a specific inventory item.

    Attributes:
        supplier_id:
            Supplier identifier.

        item_id:
            Unique inventory item identifier.

        dependency_level:
            Degree of supplier concentration.

        risk_level:
            Overall risk classification.

        supplier_count:
            Number of suppliers available for the item.
    """

    supplier_id: str
    item_id: str

    dependency_level: SupplierDependencyLevel
    risk_level: RiskLevel

    supplier_count: int

    def __post_init__(self) -> None:
        """Validate supplier risk result."""
        if self.supplier_count < 1:
            raise ValueError("supplier_count must be positive.")


@dataclass(frozen=True, slots=True)
class ReplenishmentRecommendation:
    """Recommend quantity required to restore an item to its target inventory level.

    POV can safely be assumed as the data for previous day's demand
    as orders are only placed after items are used or sold.
    Closing Stock shows the baseline or target stock level.

    Attributes:
        item_id:
            Inventory item identifier.

        baseline_stock_level:
            Target stock level (closing-stock).

        estimate_stock_level:
            Current estimated stock level of the company.

        replenishment_quantity:
            Suggested replenishment quantity (the difference).
    """

    item_id: str

    baseline_stock_level: float
    estimate_stock_level: float

    replenishment_quantity: float

    def __post_init__(self) -> None:
        """Validate replenishment recommendation."""
        if self.baseline_stock_level < 0:
            raise ValueError("baseline stock level cannot be negative.")

        if self.estimate_stock_level < 0:
            raise ValueError("estimated stock level cannot be negative.")

        if self.replenishment_quantity < 0:
            raise ValueError("replenishment quantity cannot be negative.")


@dataclass(frozen=True, slots=True)
class InventoryHealthReport:
    """Inventory condition assessment for a single item.

    Summarizes inventory status and highlights potential
    overstocking or stockout risks.

    Attributes:
        item_id:
            Inventory item identifier.

        status:
            Inventory health classification.

        months_of_cover:
            Estimated inventory coverage based on projected demand.

        excess_inventory_value:
            Monetary value of inventory exceeding expected requirements.
    """

    item_id: str

    status: InventoryStatus

    months_of_cover: float
    excess_inventory_value: float

    def __post_init__(self) -> None:
        """Validate inventory health report."""
        if self.months_of_cover < 0:
            raise ValueError("months_of_cover cannot be negative.")

        if self.excess_inventory_value < 0:
            raise ValueError("excess_inventory_value cannot be negative.")


@dataclass(frozen=True, slots=True)
class AnalyticsSummary:
    """Consolidated output of the analytics pipeline.

    Serves as the orchestration-layer result object and
    provides a unified view of all generated analytics.

    Attributes:
        forecasts:
            Forecast result for analysed items.

        supplier_risks:
            Supplier risk assessments.

        replenishment_recommendations:
            Inventory replenishment recommendations.

        inventory_health:
            Inventory health evaluations.
    """

    forecasts: tuple[ForecastResult, ...]

    supplier_risks: tuple[SupplierRisk, ...]

    replenishment_recommendations: tuple[ReplenishmentRecommendation, ...]

    inventory_health: tuple[InventoryHealthReport, ...]
