"""Canonical domain models for the inventory forecasting system.

These models define the business contracts exchanged between
application layers. They are intentionally independent of
Polars, StatsForecast, Excel workbooks, dashboards, and
external infrastructure.

Engine modules perform calculations.

Domain models describe business reality.
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from .enums import (
    AbcClass,
    ForecastModel,
    ForecastStatus,
    InventoryStatus,
    RiskLevel,
    SbcClass,
    SourceKind,
    SupplierDependencyLevel,
    TrendDirection,
)


class SourceSet(BaseModel):
    """The grouped input files for a single pipeline run.

    Each ERP report type may arrive as several files (e.g. one per year —
    INPUT_SCHEMA.md "Multiple yearly input files"), so each field is a tuple of
    paths. Tuples (not lists) keep the model genuinely immutable and hashable,
    supporting reproducibility (Constitution Rule 9). File existence/validity is
    checked later at the ingestion boundary, not here.
    """

    model_config = ConfigDict(frozen=True)

    pov: tuple[Path, ...] = ()
    grn: tuple[Path, ...] = ()
    pv: tuple[Path, ...] = ()
    closing_stock: tuple[Path, ...] = ()

    def iter_with_kind(self) -> Iterator[tuple[Path, SourceKind]]:
        """Yield every (path, kind) pair across all four report groups.

        Ingestion will loop over this to dispatch each file to the right
        reader, so the (path, kind) pairing lives with the data, not in caller
        code.
        """
        for path in self.pov:
            yield path, SourceKind.POV
        for path in self.grn:
            yield path, SourceKind.GRN
        for path in self.pv:
            yield path, SourceKind.PV
        for path in self.closing_stock:
            yield path, SourceKind.CLOSING_STOCK

    @property
    def all_paths(self) -> tuple[Path, ...]:
        """All input paths across the four groups, in canonical order."""
        return self.pov + self.grn + self.pv + self.closing_stock


class WorkbookMeta(BaseModel):
    """Provenance and run statistics written to the Metadata sheet.

    Mirrors the Metadata sheet columns in WORKBOOK_SCHEMA.md and the authenticity
    controls in THREAT_MODEL.md. `generated_at` is the only sanctioned place for
    wall-clock time (Constitution Rule 9): it lives in metadata, never in
    business logic.
    """

    model_config = ConfigDict(frozen=True)

    schema_version: str
    application_version: str
    generated_at: datetime
    forecast_horizon: int = Field(gt=0)
    total_suppliers: int = Field(ge=0)
    total_items: int = Field(ge=0)
    total_records: int = Field(ge=0)
    processing_time_seconds: float = Field(ge=0.0)


@dataclass(frozen=True, slots=True)
class AbcClassification:
    """Business Intelligence view of an item's ABC classification."""

    supplier_id: str
    item_id: str

    annual_value: Decimal

    quantity_bought: float

    revenue_percentage: float
    cumulative_revenue_percentage: float

    quantity_percentage: float
    cumulative_quantity_percentage: float

    abc_class: AbcClass

    def __post_init__(self) -> None:
        """Validate ABC classification metrics."""
        if self.annual_value < Decimal("0"):
            raise ValueError("annual_value cannot be negative.")

        if self.quantity_bought < 0:
            raise ValueError("quantity_bought cannot be negative.")

        if not 0.0 <= self.revenue_percentage <= 1.0:
            raise ValueError("revenue_percentage must be between 0 and 1.")

        if not 0.0 <= self.cumulative_revenue_percentage <= 1.0:
            raise ValueError("cumulative_revenue_percentage must be between 0 and 1.")

        if not 0.0 <= self.quantity_percentage <= 1.0:
            raise ValueError("quantity_percentage must be between 0 and 1.")

        if not 0.0 <= self.cumulative_quantity_percentage <= 1.0:
            raise ValueError("cumulative_quantity_percentage must be between 0 and 1.")


@dataclass(frozen=True, slots=True)
class DemandCharacteristics:
    """Statistical profile of an item's historical demand.

    Generated by the demand-classification subsystem and used
    to determine the most appropriate forecasting strategy.
    """

    item_id: str

    history_length: int

    mean_demand: float
    std_demand: float

    adi: float
    cv2: float

    zero_demand_ratio: float

    demand_class: SbcClass

    def __post_init__(self) -> None:
        """Validate demand characteristics."""
        if self.history_length <= 0:
            raise ValueError("history_length must be positive.")

        if self.adi < 0:
            raise ValueError("adi must be positive.")

        if self.cv2 < 0:
            raise ValueError("cv2 must be positive.")

        if not 0.0 <= self.zero_demand_ratio <= 1.0:
            raise ValueError("zero_demand_ratio must be between 0 and 1.0.")


@dataclass(frozen=True, slots=True)
class DemandObservation:
    """Reconstructed demand event derived from inventory replenishment behaviour."""

    item_id: str
    observation_date: date
    quantity: float

    def __post_init__(self) -> None:
        """Validate demand observation result."""
        if self.quantity < 0:
            raise ValueError("quantity cannot be negative.")


@dataclass(frozen=True, slots=True)
class ForecastRequest:
    """Input contract for forecast generation."""

    item_id: str
    horizon: int
    seasonality: int
    service_level: float

    def __post_init__(self) -> None:
        """Validate forecast request."""
        if self.horizon <= 0:
            raise ValueError("horizon must be positive.")

        if self.seasonality <= 0:
            raise ValueError("seasonality must be positive.")

        if not 0.0 <= self.service_level <= 1.0:
            raise ValueError("service_level must be between 0 and 1.0.")


@dataclass(frozen=True, slots=True)
class ForecastMetrics:
    """Forecast performance metrics produced during model evaluation and backtesting."""

    mase: float
    rmsse: float
    bias: float
    mae: float
    rmse: float
    observation_count: int

    def __post_init__(self) -> None:
        """Validate metric values."""
        if self.mase < 0:
            raise ValueError("MASE cannot be negative.")

        if self.rmsse < 0:
            raise ValueError("RMSSE cannot be negative.")

        if self.mae < 0:
            raise ValueError("MAE cannot be negative.")

        if self.rmse < 0:
            raise ValueError("RMSE cannot be negative.")

        if self.observation_count <= 0:
            raise ValueError("Observation count must be positive.")


@dataclass(frozen=True, slots=True)
class ForecastResult:
    """Final demand forecast produced for an inventory item."""

    item_id: str
    demand_class: SbcClass
    selected_model: ForecastModel
    forecast_values: tuple[float, ...]
    lower_bound: tuple[float, ...]
    upper_bound: tuple[float, ...]
    metrics: ForecastMetrics
    status: ForecastStatus
    generated_at: datetime

    def __post_init__(self) -> None:
        """Validate forecast result."""
        expected = len(self.forecast_values)

        if expected == 0:
            raise ValueError("forecast_values cannot be empty.")

        if len(self.lower_bound) != expected:
            raise ValueError("lower_bound length must match forecast_values length.")

        if len(self.upper_bound) != expected:
            raise ValueError("upper_bound length must match forecast_values length.")


@dataclass(frozen=True, slots=True)
class SupplierPerformance:
    """Historical supplier performance metrics for an item."""

    supplier_id: str
    item_id: str

    avg_lead_time_days: float
    lead_time_std_dev: float
    avg_fill_rate: float


@dataclass(frozen=True, slots=True)
class SupplierRisk:
    """Supplier concentration and dependency risk assessment for a specific supplier."""

    supplier_id: str
    item_id: str

    dependency_level: SupplierDependencyLevel
    risk_level: RiskLevel

    supplier_count: int

    def __post_init__(self) -> None:
        """Validate supplier risk result."""
        if self.supplier_count < 1:
            raise ValueError("supplier_count must be positive.")


@dataclass(frozen=True, slots=True)
class ReplenishmentRecommendation:
    """Recommend quantity required to restore an item to its target inventory level."""

    item_id: str

    baseline_stock_level: float
    estimate_stock_level: float
    replenishment_quantity: float

    def __post_init__(self) -> None:
        """Validate replenishment recommendation."""
        if self.baseline_stock_level < 0:
            raise ValueError("baseline stock level cannot be negative.")

        if self.estimate_stock_level < 0:
            raise ValueError("estimated stock level cannot be negative.")

        if self.replenishment_quantity < 0:
            raise ValueError("replenishment quantity cannot be negative.")


@dataclass(frozen=True, slots=True)
class InventoryHealthReport:
    """Inventory condition assessment for a single item."""

    item_id: str

    status: InventoryStatus

    months_of_cover: float
    excess_inventory_value: float

    def __post_init__(self) -> None:
        """Validate inventory health report."""
        if self.months_of_cover < 0:
            raise ValueError("months_of_cover cannot be negative.")

        if self.excess_inventory_value < 0:
            raise ValueError("excess_inventory_value cannot be negative.")


# ======================================================================================
# Business Intelligence Platform Models
# ======================================================================================


@dataclass(frozen=True, slots=True)
class ExecutiveMetric:
    """High-level KPI for executive summary dashboard."""

    category: str
    metric_name: str
    value: float
    trend: TrendDirection
    status: str


@dataclass(frozen=True, slots=True)
class DashboardPanelData:
    """Pre-computed visualization data for dashboards.

    Used to drive Plotly dashboards without requiring in-memory
    aggregation or repeated Polars queries.
    """

    panel_id: str
    dimension: str
    metric: str
    value: float
    percentage: float


@dataclass(frozen=True, slots=True)
class ProcurementInsight:
    """Actionable insight for procurement managers."""

    insight_type: str
    priority: RiskLevel
    description: str
    affected_items: int
    potential_impact: float


@dataclass(frozen=True, slots=True)
class SourcingRiskReport:
    """Item-level supplier dependency risk for procurement strategy."""

    item_id: str
    supplier_count: int
    primary_supplier: str
    dependency_level: SupplierDependencyLevel
    risk_level: RiskLevel

    def __post_init__(self) -> None:
        """Validate sourcing risk report."""
        if self.supplier_count < 0:
            raise ValueError("supplier_count cannot be negative.")


# ======================================================================================
# Orchestration Output
# ======================================================================================


@dataclass(frozen=True, slots=True)
class AnalyticsSummary:
    """Consolidated output of the analytics pipeline.

    Serves as the orchestration-layer result object and
    provides a unified view of all generated analytics.
    """

    # Existing Forecasting & Replenishment
    forecasts: tuple[ForecastResult, ...]
    supplier_risks: tuple[SupplierRisk, ...]
    replenishment_recommendations: tuple[ReplenishmentRecommendation, ...]
    inventory_health: tuple[InventoryHealthReport, ...]

    abc_classification: tuple[AbcClassification, ...] = ()

    # Business Intelligence Platform Extensions
    executive_metrics: tuple[ExecutiveMetric, ...] = ()
    dashboard_data: tuple[DashboardPanelData, ...] = ()
    procurement_insights: tuple[ProcurementInsight, ...] = ()
    sourcing_risks: tuple[SourcingRiskReport, ...] = ()
