"""Unclassified Inventory Diagnostic Engine.

This script audits the UNCLASSIFIED baseline inventory against the authoritative
Item Master list to determine if the mapping failures are caused by typographical
variations, casing/spacing issues, or if the items represent genuine legacy
dead stock lacking recent procurement activity.
"""

import argparse
import difflib
from pathlib import Path

import polars as pl


def audit_unclassified_stock(analytics_file: Path, verbose: bool = False) -> None:
    """Analyze the Unclassified inventory for potential fuzzy string matches.

    Reads the output sheets generated by the data understanding script, extracts
    unique unclassified entries from current baseline stock records, and runs a
    high-similarity ratio check against item descriptions recorded in historical
    procurement ledgers (PV/POV).

    Args:
        analytics_file: Path to the Excel spreadsheet containing the
            pre-calculated exploratory summaries.
        verbose: If True, enables detailed log printing for every close
            match found.

    Returns:
        None.
    """
    if verbose:
        print(f"Reading analytics workbook: {analytics_file}")

    # Read the dataframes from the previously compiled understanding workbook
    stock_df = pl.read_excel(analytics_file, sheet_name="Raw_Mapped_Stock")
    abc_df = pl.read_excel(analytics_file, sheet_name="Item_ABC_Master")

    # Isolate unique UNCLASSIFIED items from physical inventory snapshots
    unclassified_items = (
        stock_df.filter(pl.col("abc_class") == "UNCLASSIFIED")
        .select("item")
        .unique()
        .to_series()
        .to_list()
    )

    # Isolate the master list of items with valid historical transactions
    valid_items = abc_df.select("item").unique().to_series().to_list()

    print("\n--- Diagnostic Run Results ---")
    print(f"Total Valid PV/POV Items: {len(valid_items)}")
    print(f"Total Unclassified Physical Items: {len(unclassified_items)}")
    print("\nScanning for string mismatches (Similarity Threshold > 85%)...")

    mismatches_found = 0
    # Process a representative sample to quickly characterize string drift behavior
    for missing_item in unclassified_items[:200]:
        matches = difflib.get_close_matches(missing_item, valid_items, n=1, cutoff=0.85)

        if matches:
            mismatches_found += 1
            print("[POTENTIAL MATCH FOUND]")
            print(f"  Stock Name  : '{missing_item}'")
            print(f"  Ledger Name : '{matches[0]}'")

    print("\n--- Summary Conclusions ---")
    if mismatches_found > 0:
        print(
            f"Conclusion: Detected {mismatches_found} naming discrepancies "
            f"within a 200-item sample."
        )
        print(
            "Required Strategy: The ingestion layer requires "
            "string normalization filters "
        )
        print(
            "(e.g., lowercase conversion, trimming, punctuation strips) "
            "before executing joins."
        )
    else:
        print("Conclusion: 0 string matches identified.")
        print(
            "Required Strategy: These are true legacy holdings or "
            "manufactured WIP components."
        )
        print(
            "We must append a separate master catalog rule to "
            "auto-classify them cleanly."
        )


def main() -> None:
    """Provide the main entry point execution block for the diagnostic script.

    Parses input workbook targets and initiates the string similarity comparison.
    """
    parser = argparse.ArgumentParser(
        description="Audit unclassified baseline inventory for description drift."
    )
    parser.add_argument(
        "-f",
        "--file",
        type=Path,
        required=True,
        help="Path to the compiled data_understanding.xlsx analytics file.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable descriptive stdout logging tracking data transformations.",
    )
    args = parser.parse_args()

    audit_unclassified_stock(args.file, args.verbose)


if __name__ == "__main__":
    main()
