"""CLI entry point for forecast validation.

Supports:

1. Temporal holdout validation
2. Rolling-origin validation

The validation layer operates directly against the
Demand_History contract generated by reconstruct_demand().
"""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

import polars as pl

from opstools.inventory_forecast.config import Settings
from opstools.inventory_forecast.domain import SourceKind
from opstools.inventory_forecast.engine.classification import (
    classify_sbc,
)
from opstools.inventory_forecast.engine.demand import (
    reconstruct_demand,
)
from opstools.inventory_forecast.engine.forecasting import (
    forecast_demand,
)
from opstools.inventory_forecast.ingestion import (
    read_source,
)
from opstools.inventory_forecast.validation import (
    BacktestEvaluator,
    export_validation_report,
    run_rolling_origin,
)


def forecast_adapter(
    demand: pl.DataFrame,
    settings: Settings,
) -> pl.DataFrame:
    """Adapt engine forecasting API to validation API."""

    demand_lf = demand.lazy()

    sbc_lf = classify_sbc(
        demand_lf,
    )

    forecast_lf = forecast_demand(
        demand=demand_lf,
        sbc=sbc_lf,
        horizon=settings.forecast_horizon,
        cfg=settings,
    )

    return forecast_lf.collect()


def _load_demand_history(
    pov_path: Path,
) -> pl.DataFrame:
    """Load and reconstruct demand history."""

    pov = read_source(
        pov_path,
        SourceKind.POV,
    )

    return reconstruct_demand(
        pov,
    ).collect()


def _run_holdout(
    *,
    demand: pl.DataFrame,
    cutoff: date,
    settings: Settings,
    output_path: Path,
) -> int:
    """Execute temporal holdout validation."""

    train_demand = demand.filter(
        pl.col("period") < cutoff,
    )

    test_demand = demand.filter(
        pl.col("period") >= cutoff,
    )

    if train_demand.is_empty():
        raise ValueError("Training demand became empty after cutoff.")

    if test_demand.is_empty():
        raise ValueError("Test demand became empty after cutoff.")

    evaluator = BacktestEvaluator(
        forecast_callback=forecast_adapter,
        settings=settings,
    )

    result = evaluator.evaluate(
        train_demand=train_demand,
        test_demand=test_demand,
    )

    export_validation_report(
        output_path=output_path,
        metrics=result.aggregate_metrics,
        timeseries=result.forecast_vs_actual,
        cutoff_date=str(cutoff),
        sku_metrics=result.sku_metrics,
    )

    print(f"Validation workbook written to: {output_path}")

    return 0


def _run_rolling(
    *,
    demand: pl.DataFrame,
    settings: Settings,
    output_path: Path,
) -> int:
    """Execute rolling-origin validation."""

    result = run_rolling_origin(
        demand=demand,
        forecast_callback=forecast_adapter,
        settings=settings,
    )

    export_validation_report(
        output_path=output_path,
        metrics=result.aggregate_metrics,
        timeseries=result.forecast_vs_actual,
        cutoff_date="rolling-origin",
        fold_metrics=result.fold_metrics,
    )

    print(f"Rolling-origin workbook written to: {output_path}")

    return 0


def main() -> int:
    """Execute forecast validation."""

    parser = argparse.ArgumentParser(description="Inventory forecast validation.")

    parser.add_argument(
        "--pov",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--out",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--cutoff",
        type=date.fromisoformat,
        help="YYYY-MM-DD holdout split date.",
    )

    parser.add_argument(
        "--rolling",
        action="store_true",
        help="Run rolling-origin validation.",
    )

    args = parser.parse_args()

    settings = Settings()

    print("Loading demand history...")

    demand = _load_demand_history(
        args.pov,
    )

    try:
        if args.rolling:
            return _run_rolling(
                demand=demand,
                settings=settings,
                output_path=args.out,
            )

        if args.cutoff is None:
            raise ValueError("--cutoff is required when --rolling is not specified.")

        return _run_holdout(
            demand=demand,
            cutoff=args.cutoff,
            settings=settings,
            output_path=args.out,
        )

    except ValueError as exc:
        print(f"Validation failed: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
