[package]
name = "kepl-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "kepl_core"
crate-type = ["rlib"]

[dependencies]
polars = { version = "0.53.0", default-features = false, features = ["lazy", "dtype-date", "dtype-datetime", "parquet", "cum_agg", "strings", "regex", "temporal", "csv", "cloud"] }
polars_excel_writer = "0.25.0"
rust_decimal = { version = "1.42", default-features = false, features = ["maths"] }
rust_decimal_macros = "1.40"
chrono = { version = "0.4.41", default-features = false, features = ["serde", "clock", "std"] }
thiserror = { version = "2.0.18", default-features = false }
serde = { version = "1.0.218", default-features = false, features = ["derive"] }
log = { version = "0.4.22", default-features = false }
calamine = { version = "0.22", features = ["dates"] }